config_data: |
  extends: default
  rules:
    new-line-at-end-of-file:
      level: disable
    comments:
      level: disable
    line-length:
      level: disable
    trailing-spaces:
      level: disable
